#!python

import os
import sys

import argparse
import fp_tools


# Parse command line arguments
parser = argparse.ArgumentParser(
    description="Cut a data-cube in the spectral direction.")

parser.add_argument(
    'input_cube', type=str,
    help="Input cube.")
parser.add_argument(
    'output_cube', type=str,
    help="Output cube.")
parser.add_argument(
    '--n_begin', type=int, default=None,
    help="Cut channel at the beginning of the cube.")
parser.add_argument(
    '--n_end', type=int, default=None,
    help="Cut channel at the end of the cube. Use negative values to count the "
         "channels backwards (e.g. -10 excludes the last 10 channels).")

args = parser.parse_args()

# Check before running
if not os.path.exists(args.input_cube):
    print("\n Input file does not exists: %s\n Leaving now." % args.input_cube)
    sys.exit(1)

if os.path.exists(args.output_cube):
    print("\n Output file exists: %s" % args.output_cube)
    print(" Delete it before running this.\n Leaving now.")
    sys.exit(1)

# Running scripts
fp_cut = fp_tools.tools_3d.z_cut(args.input_cube, args.output_cube,
                                 n_begin=args.n_begin, n_end=args.n_end)

fp_cut.start()
fp_cut.join()
